Fix issue #6 and #10
teragrep/jpr_01 pull request #12
Opened 2023-02-21 13:38 UTC by Tiihott

Attempt at fixing issues #6 and #10

2023-02-21 13:41 UTC, kortemik approved these changes
fixes issue #6 and #10

2023-02-21 13:42 UTC, kortemik requested changes

2023-02-21 13:42 UTC, kortemik commented on src/main/java/com/teragrep/jpr_01/JavaPcre.java
> +    public Map<String, Integer> name_table;
instead of direct member field access, change to getter pattern

2023-02-21 13:43 UTC, kortemik commented on src/main/java/com/teragrep/jpr_01/JavaPcre.java
> +    public Map<String, Integer> name_table;
please also make all member fields private, if not absolutely required to be package-private

2023-02-21 13:44 UTC, kortemik commented
please move [JavaPcreTest.java](https://github.com/teragrep/jpr_01/blob/main/src/test/java/com/teragrep/JavaPcreTest.java) to jpr_01.tests

2023-02-22 14:19 UTC, Tiihott commented
All fields should now be set to private with added get-functions. Also removed "pcre2_" from function names where it is not needed for better clarity.

2023-02-22 15:28 UTC, kortemik approved these changes
Requested changes seem to be implemented correctly. Thanks a lot!

2023-02-22 15:28 UTC, merged